Font = require("core.font")
Gamestate = require("libs.hump.gamestate")
TitleScene = require("scenes.title")
DrawScene = require("scenes.draw")
ResultScene = require("scenes.result")
SettingsScene = require("scenes.settings")
AudioMgr = require("systems.audio_manager")
Config = require("core.config")

function love.load()
    math.randomseed(os.time())
    AudioMgr:load()
    Gamestate.registerEvents()
    Gamestate.switch(TitleScene)
end
